/** Shortlist of commonly-ordered-from Indian cities/towns, used to back a
 * searchable suggestion list for the "City" field. Unlike state (a closed,
 * fixed set — see indianStates.ts), India has thousands of towns, so this
 * list is a convenience, not exhaustive: the City combobox lets the shopper
 * type a name that isn't here and use it as-is rather than blocking them. */
export const INDIAN_CITIES: string[] = [
  "Agra",
  "Ahmedabad",
  "Ajmer",
  "Aligarh",
  "Allahabad (Prayagraj)",
  "Amritsar",
  "Aurangabad",
  "Bareilly",
  "Bengaluru",
  "Bhopal",
  "Bhubaneswar",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Faridabad",
  "Ghaziabad",
  "Gorakhpur",
  "Guntur",
  "Guwahati",
  "Gwalior",
  "Hubballi-Dharwad",
  "Hyderabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jammu",
  "Jamshedpur",
  "Jodhpur",
  "Kanpur",
  "Kochi",
  "Kolhapur",
  "Kolkata",
  "Kota",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mathura",
  "Meerut",
  "Mumbai",
  "Mysuru",
  "Nagpur",
  "Nashik",
  "Navi Mumbai",
  "Noida",
  "Patna",
  "Puducherry",
  "Pune",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Salem",
  "Shimla",
  "Siliguri",
  "Solapur",
  "Srinagar",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Tiruchirappalli",
  "Udaipur",
  "Vadodara",
  "Varanasi",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
];
