/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyPolicyRouteImport } from './routes/warranty-policy'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CategoryNameRouteImport } from './routes/category.$name'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp-webhook'
import { Route as ApiVerifyRazorpayPaymentRouteImport } from './routes/api.verify-razorpay-payment'
import { Route as ApiRefundRazorpayPaymentRouteImport } from './routes/api.refund-razorpay-payment'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api.razorpay-webhook'
import { Route as ApiCreateRazorpayOrderRouteImport } from './routes/api.create-razorpay-order'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as OrdersIdTrackRouteImport } from './routes/orders.$id.track'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const WarrantyPolicyRoute = WarrantyPolicyRouteImport.update({
  id: '/warranty-policy',
  path: '/warranty-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRazorpayPaymentRoute =
  ApiVerifyRazorpayPaymentRouteImport.update({
    id: '/api/verify-razorpay-payment',
    path: '/api/verify-razorpay-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRefundRazorpayPaymentRoute =
  ApiRefundRazorpayPaymentRouteImport.update({
    id: '/api/refund-razorpay-payment',
    path: '/api/refund-razorpay-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay-webhook',
  path: '/api/razorpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateRazorpayOrderRoute = ApiCreateRazorpayOrderRouteImport.update({
  id: '/api/create-razorpay-order',
  path: '/api/create-razorpay-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const OrdersIdTrackRoute = OrdersIdTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => OrdersIdRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/category/$name': typeof CategoryNameRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/category/$name': typeof CategoryNameRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/wallet': typeof AdminWalletRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/category/$name': typeof CategoryNameRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/wallet'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/category/$name'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/users/$id'
    | '/orders/$id/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/wallet'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/category/$name'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/users/$id'
    | '/orders/$id/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/profile'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/admin/wallet'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/category/$name'
    | '/orders/$id'
    | '/product/$slug'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/users/$id'
    | '/orders/$id/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  WarrantyPolicyRoute: typeof WarrantyPolicyRoute
  ApiCreateRazorpayOrderRoute: typeof ApiCreateRazorpayOrderRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
  ApiRefundRazorpayPaymentRoute: typeof ApiRefundRazorpayPaymentRoute
  ApiVerifyRazorpayPaymentRoute: typeof ApiVerifyRazorpayPaymentRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  CategoryNameRoute: typeof CategoryNameRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty-policy': {
      id: '/warranty-policy'
      path: '/warranty-policy'
      fullPath: '/warranty-policy'
      preLoaderRoute: typeof WarrantyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-razorpay-payment': {
      id: '/api/verify-razorpay-payment'
      path: '/api/verify-razorpay-payment'
      fullPath: '/api/verify-razorpay-payment'
      preLoaderRoute: typeof ApiVerifyRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refund-razorpay-payment': {
      id: '/api/refund-razorpay-payment'
      path: '/api/refund-razorpay-payment'
      fullPath: '/api/refund-razorpay-payment'
      preLoaderRoute: typeof ApiRefundRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay-webhook': {
      id: '/api/razorpay-webhook'
      path: '/api/razorpay-webhook'
      fullPath: '/api/razorpay-webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-razorpay-order': {
      id: '/api/create-razorpay-order'
      path: '/api/create-razorpay-order'
      fullPath: '/api/create-razorpay-order'
      preLoaderRoute: typeof ApiCreateRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orders/$id/track': {
      id: '/orders/$id/track'
      path: '/track'
      fullPath: '/orders/$id/track'
      preLoaderRoute: typeof OrdersIdTrackRouteImport
      parentRoute: typeof OrdersIdRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminProductsRoute: AdminProductsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OrdersIdRouteChildren {
  OrdersIdTrackRoute: typeof OrdersIdTrackRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdTrackRoute: OrdersIdTrackRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRouteWithChildren,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  WarrantyPolicyRoute: WarrantyPolicyRoute,
  ApiCreateRazorpayOrderRoute: ApiCreateRazorpayOrderRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
  ApiRefundRazorpayPaymentRoute: ApiRefundRazorpayPaymentRoute,
  ApiVerifyRazorpayPaymentRoute: ApiVerifyRazorpayPaymentRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  CategoryNameRoute: CategoryNameRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
