/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
//
// MANUALLY CORRECTED on 2026-07-19: the committed version of this file had
// drifted out of sync with src/routes (missing admin.taxonomy, orders.$id,
// admin.delivery/returns/wallet, wallet, category.$name, search, and every
// api.* route). This build's regeneration step wasn't picking those up —
// see vite.config.ts / deployment target notes. Once that's sorted, running
// `vite build` (or `vite dev`) will regenerate this file automatically and
// safely overwrite this manual fix.
//
// MANUALLY CORRECTED AGAIN on 2026-07-25: the 2026-07-19 fix above still
// missed four existing routes (api.rate-limit, api.send-phone-otp,
// api.verify-captcha, api.verify-phone-otp) that were on disk in src/routes
// but never made it into this file, so they 404'd in production. Added
// those plus the new api.geocode route (see src/routes/api.geocode.ts).
// If you fix the regeneration step, delete both manual-correction notes —
// this whole file gets safely overwritten on the next `vite build`/`vite dev`.
//
// MANUALLY CORRECTED AGAIN on 2026-07-31: added the new support ticket
// routes (support, support.$id, admin.support, admin.support.$id) plus
// api.support-notify for the same reason as above.
//
// MANUALLY CORRECTED AGAIN on 2026-08-01: added the new /collections route.
//
// MANUALLY CORRECTED AGAIN on 2026-08-11: added the entire /admin/analytics
// section (layout route + index/users/geographic/traffic/business/errors/
// realtime/alerts/reports children), which existed on disk in src/routes
// but had never been added here, so the whole section was unreachable in
// any build that skips the regeneration step. Registered the children as
// true children of AdminAnalyticsRoute (not flattened under AdminRoute
// like the other admin.*.$id routes), since admin.analytics.tsx renders
// them through its own <Outlet />.
//
// MANUALLY CORRECTED AGAIN same day (2026-08-11): the pass above only
// added the admin *pages*, not the five api.analytics-*.ts server routes
// they depend on (alerts-check, cleanup, error, reports-run, track) —
// those existed on disk too but were still missing here, so every
// analytics API call was 404ing even though the pages themselves loaded.
// Added as flat root-level routes, same pattern as api.support-notify.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as WarrantyPolicyRouteImport } from './routes/warranty-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersIdTrackRouteImport } from './routes/orders.$id.track'
import { Route as CategoryNameRouteImport } from './routes/category.$name'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminTaxonomyRouteImport } from './routes/admin.taxonomy'
import { Route as AdminReturnsRouteImport } from './routes/admin.returns'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin.analytics.index'
import { Route as AdminAnalyticsUsersRouteImport } from './routes/admin.analytics.users'
import { Route as AdminAnalyticsGeographicRouteImport } from './routes/admin.analytics.geographic'
import { Route as AdminAnalyticsTrafficRouteImport } from './routes/admin.analytics.traffic'
import { Route as AdminAnalyticsBusinessRouteImport } from './routes/admin.analytics.business'
import { Route as AdminAnalyticsErrorsRouteImport } from './routes/admin.analytics.errors'
import { Route as AdminAnalyticsRealtimeRouteImport } from './routes/admin.analytics.realtime'
import { Route as AdminAnalyticsAlertsRouteImport } from './routes/admin.analytics.alerts'
import { Route as AdminAnalyticsReportsRouteImport } from './routes/admin.analytics.reports'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp-webhook'
import { Route as ApiGeocodeRouteImport } from './routes/api.geocode'
import { Route as ApiRateLimitRouteImport } from './routes/api.rate-limit'
import { Route as ApiSendPhoneOtpRouteImport } from './routes/api.send-phone-otp'
import { Route as ApiVerifyCaptchaRouteImport } from './routes/api.verify-captcha'
import { Route as ApiVerifyPhoneOtpRouteImport } from './routes/api.verify-phone-otp'
import { Route as ApiVerifyRazorpayPaymentRouteImport } from './routes/api.verify-razorpay-payment'
import { Route as ApiRefundRazorpayPaymentRouteImport } from './routes/api.refund-razorpay-payment'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api.razorpay-webhook'
import { Route as ApiCreateRazorpayOrderRouteImport } from './routes/api.create-razorpay-order'
import { Route as ApiOrderNotifyRouteImport } from './routes/api.order-notify'
import { Route as ApiPaymentNotifyRouteImport } from './routes/api.payment-notify'
import { Route as ApiReturnNotifyRouteImport } from './routes/api.return-notify'
import { Route as ApiPushSubscribeRouteImport } from './routes/api.push-subscribe'
import { Route as ApiVapidPublicKeyRouteImport } from './routes/api.vapid-public-key'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as ApiSupportNotifyRouteImport } from './routes/api.support-notify'
import { Route as ApiAnalyticsAlertsCheckRouteImport } from './routes/api.analytics-alerts-check'
import { Route as ApiAnalyticsCleanupRouteImport } from './routes/api.analytics-cleanup'
import { Route as ApiAnalyticsErrorRouteImport } from './routes/api.analytics-error'
import { Route as ApiAnalyticsReportsRunRouteImport } from './routes/api.analytics-reports-run'
import { Route as ApiAnalyticsTrackRouteImport } from './routes/api.analytics-track'
import { Route as ApiSearchLogRouteImport } from './routes/api.search-log'
import { Route as ApiAnalyticsVitalsRouteImport } from './routes/api.analytics-vitals'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SupportIdRouteImport } from './routes/support.$id'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSupportIdRouteImport } from './routes/admin.support.$id'
import { Route as AdminAiConsoleRouteImport } from './routes/admin.ai-console'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as ApiAiConsoleRouteImport } from './routes/api.ai-console'
import { Route as ApiValidateCouponRouteImport } from './routes/api.validate-coupon'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyPolicyRoute = WarrantyPolicyRouteImport.update({
  id: '/warranty-policy',
  path: '/warranty-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdTrackRoute = OrdersIdTrackRouteImport.update({
  id: '/orders/$id/track',
  path: '/orders/$id/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryNameRoute = CategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaxonomyRoute = AdminTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsUsersRoute = AdminAnalyticsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsGeographicRoute = AdminAnalyticsGeographicRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsTrafficRoute = AdminAnalyticsTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsBusinessRoute = AdminAnalyticsBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsErrorsRoute = AdminAnalyticsErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsRealtimeRoute = AdminAnalyticsRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsAlertsRoute = AdminAnalyticsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsReportsRoute = AdminAnalyticsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRateLimitRoute = ApiRateLimitRouteImport.update({
  id: '/api/rate-limit',
  path: '/api/rate-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendPhoneOtpRoute = ApiSendPhoneOtpRouteImport.update({
  id: '/api/send-phone-otp',
  path: '/api/send-phone-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyCaptchaRoute = ApiVerifyCaptchaRouteImport.update({
  id: '/api/verify-captcha',
  path: '/api/verify-captcha',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPhoneOtpRoute = ApiVerifyPhoneOtpRouteImport.update({
  id: '/api/verify-phone-otp',
  path: '/api/verify-phone-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRazorpayPaymentRoute = ApiVerifyRazorpayPaymentRouteImport.update({
  id: '/api/verify-razorpay-payment',
  path: '/api/verify-razorpay-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefundRazorpayPaymentRoute = ApiRefundRazorpayPaymentRouteImport.update({
  id: '/api/refund-razorpay-payment',
  path: '/api/refund-razorpay-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay-webhook',
  path: '/api/razorpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateRazorpayOrderRoute = ApiCreateRazorpayOrderRouteImport.update({
  id: '/api/create-razorpay-order',
  path: '/api/create-razorpay-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderNotifyRoute = ApiOrderNotifyRouteImport.update({
  id: '/api/order-notify',
  path: '/api/order-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentNotifyRoute = ApiPaymentNotifyRouteImport.update({
  id: '/api/payment-notify',
  path: '/api/payment-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReturnNotifyRoute = ApiReturnNotifyRouteImport.update({
  id: '/api/return-notify',
  path: '/api/return-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push-subscribe',
  path: '/api/push-subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapidPublicKeyRoute = ApiVapidPublicKeyRouteImport.update({
  id: '/api/vapid-public-key',
  path: '/api/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSupportNotifyRoute = ApiSupportNotifyRouteImport.update({
  id: '/api/support-notify',
  path: '/api/support-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsAlertsCheckRoute = ApiAnalyticsAlertsCheckRouteImport.update({
  id: '/api/analytics-alerts-check',
  path: '/api/analytics-alerts-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsCleanupRoute = ApiAnalyticsCleanupRouteImport.update({
  id: '/api/analytics-cleanup',
  path: '/api/analytics-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsErrorRoute = ApiAnalyticsErrorRouteImport.update({
  id: '/api/analytics-error',
  path: '/api/analytics-error',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsReportsRunRoute = ApiAnalyticsReportsRunRouteImport.update({
  id: '/api/analytics-reports-run',
  path: '/api/analytics-reports-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsTrackRoute = ApiAnalyticsTrackRouteImport.update({
  id: '/api/analytics-track',
  path: '/api/analytics-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchLogRoute = ApiSearchLogRouteImport.update({
  id: '/api/search-log',
  path: '/api/search-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsVitalsRoute = ApiAnalyticsVitalsRouteImport.update({
  id: '/api/analytics-vitals',
  path: '/api/analytics-vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiConsoleRoute = AdminAiConsoleRouteImport.update({
  id: '/ai-console',
  path: '/ai-console',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAiConsoleRoute = ApiAiConsoleRouteImport.update({
  id: '/api/ai-console',
  path: '/api/ai-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateCouponRoute = ApiValidateCouponRouteImport.update({
  id: '/api/validate-coupon',
  path: '/api/validate-coupon',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/category/$name': typeof CategoryNameRoute
  '/product/$slug': typeof ProductSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/users': typeof AdminAnalyticsUsersRoute
  '/admin/analytics/geographic': typeof AdminAnalyticsGeographicRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/analytics/business': typeof AdminAnalyticsBusinessRoute
  '/admin/analytics/errors': typeof AdminAnalyticsErrorsRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/alerts': typeof AdminAnalyticsAlertsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/rate-limit': typeof ApiRateLimitRoute
  '/api/send-phone-otp': typeof ApiSendPhoneOtpRoute
  '/api/verify-captcha': typeof ApiVerifyCaptchaRoute
  '/api/verify-phone-otp': typeof ApiVerifyPhoneOtpRoute
  '/api/order-notify': typeof ApiOrderNotifyRoute
  '/api/payment-notify': typeof ApiPaymentNotifyRoute
  '/api/return-notify': typeof ApiReturnNotifyRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/profile': typeof ProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/support-notify': typeof ApiSupportNotifyRoute
  '/support': typeof SupportRoute
  '/support/$id': typeof SupportIdRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/analytics-alerts-check': typeof ApiAnalyticsAlertsCheckRoute
  '/api/analytics-cleanup': typeof ApiAnalyticsCleanupRoute
  '/api/analytics-error': typeof ApiAnalyticsErrorRoute
  '/api/analytics-reports-run': typeof ApiAnalyticsReportsRunRoute
  '/api/analytics-track': typeof ApiAnalyticsTrackRoute
  '/api/search-log': typeof ApiSearchLogRoute
  '/api/analytics-vitals': typeof ApiAnalyticsVitalsRoute
  '/admin/ai-console': typeof AdminAiConsoleRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/ai-console': typeof ApiAiConsoleRoute
  '/api/validate-coupon': typeof ApiValidateCouponRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/category/$name': typeof CategoryNameRoute
  '/product/$slug': typeof ProductSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/admin': typeof AdminIndexRoute
  '/admin/analytics/users': typeof AdminAnalyticsUsersRoute
  '/admin/analytics/geographic': typeof AdminAnalyticsGeographicRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/analytics/business': typeof AdminAnalyticsBusinessRoute
  '/admin/analytics/errors': typeof AdminAnalyticsErrorsRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/alerts': typeof AdminAnalyticsAlertsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/rate-limit': typeof ApiRateLimitRoute
  '/api/send-phone-otp': typeof ApiSendPhoneOtpRoute
  '/api/verify-captcha': typeof ApiVerifyCaptchaRoute
  '/api/verify-phone-otp': typeof ApiVerifyPhoneOtpRoute
  '/api/order-notify': typeof ApiOrderNotifyRoute
  '/api/payment-notify': typeof ApiPaymentNotifyRoute
  '/api/return-notify': typeof ApiReturnNotifyRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/profile': typeof ProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/support-notify': typeof ApiSupportNotifyRoute
  '/support': typeof SupportRoute
  '/support/$id': typeof SupportIdRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/analytics-alerts-check': typeof ApiAnalyticsAlertsCheckRoute
  '/api/analytics-cleanup': typeof ApiAnalyticsCleanupRoute
  '/api/analytics-error': typeof ApiAnalyticsErrorRoute
  '/api/analytics-reports-run': typeof ApiAnalyticsReportsRunRoute
  '/api/analytics-track': typeof ApiAnalyticsTrackRoute
  '/api/search-log': typeof ApiSearchLogRoute
  '/api/analytics-vitals': typeof ApiAnalyticsVitalsRoute
  '/admin/ai-console': typeof AdminAiConsoleRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/ai-console': typeof ApiAiConsoleRoute
  '/api/validate-coupon': typeof ApiValidateCouponRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/orders': typeof OrdersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/warranty-policy': typeof WarrantyPolicyRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/returns': typeof AdminReturnsRoute
  '/admin/taxonomy': typeof AdminTaxonomyRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/category/$name': typeof CategoryNameRoute
  '/product/$slug': typeof ProductSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/orders/$id/track': typeof OrdersIdTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/users': typeof AdminAnalyticsUsersRoute
  '/admin/analytics/geographic': typeof AdminAnalyticsGeographicRoute
  '/admin/analytics/traffic': typeof AdminAnalyticsTrafficRoute
  '/admin/analytics/business': typeof AdminAnalyticsBusinessRoute
  '/admin/analytics/errors': typeof AdminAnalyticsErrorsRoute
  '/admin/analytics/realtime': typeof AdminAnalyticsRealtimeRoute
  '/admin/analytics/alerts': typeof AdminAnalyticsAlertsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/api/create-razorpay-order': typeof ApiCreateRazorpayOrderRoute
  '/api/razorpay-webhook': typeof ApiRazorpayWebhookRoute
  '/api/refund-razorpay-payment': typeof ApiRefundRazorpayPaymentRoute
  '/api/verify-razorpay-payment': typeof ApiVerifyRazorpayPaymentRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/rate-limit': typeof ApiRateLimitRoute
  '/api/send-phone-otp': typeof ApiSendPhoneOtpRoute
  '/api/verify-captcha': typeof ApiVerifyCaptchaRoute
  '/api/verify-phone-otp': typeof ApiVerifyPhoneOtpRoute
  '/api/order-notify': typeof ApiOrderNotifyRoute
  '/api/payment-notify': typeof ApiPaymentNotifyRoute
  '/api/return-notify': typeof ApiReturnNotifyRoute
  '/api/push-subscribe': typeof ApiPushSubscribeRoute
  '/api/vapid-public-key': typeof ApiVapidPublicKeyRoute
  '/profile': typeof ProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/support-notify': typeof ApiSupportNotifyRoute
  '/support': typeof SupportRoute
  '/support/$id': typeof SupportIdRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/api/analytics-alerts-check': typeof ApiAnalyticsAlertsCheckRoute
  '/api/analytics-cleanup': typeof ApiAnalyticsCleanupRoute
  '/api/analytics-error': typeof ApiAnalyticsErrorRoute
  '/api/analytics-reports-run': typeof ApiAnalyticsReportsRunRoute
  '/api/analytics-track': typeof ApiAnalyticsTrackRoute
  '/api/search-log': typeof ApiSearchLogRoute
  '/api/analytics-vitals': typeof ApiAnalyticsVitalsRoute
  '/admin/ai-console': typeof AdminAiConsoleRoute
  '/admin/search': typeof AdminSearchRoute
  '/api/ai-console': typeof ApiAiConsoleRoute
  '/api/validate-coupon': typeof ApiValidateCouponRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/wallet'
    | '/admin/analytics'
    | '/category/$name'
    | '/product/$slug'
    | '/orders/$id'
    | '/orders/$id/track'
    | '/admin/'
    | '/admin/analytics/users'
    | '/admin/analytics/geographic'
    | '/admin/analytics/traffic'
    | '/admin/analytics/business'
    | '/admin/analytics/errors'
    | '/admin/analytics/realtime'
    | '/admin/analytics/alerts'
    | '/admin/analytics/reports'
    | '/admin/analytics/'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/api/geocode'
    | '/api/rate-limit'
    | '/api/send-phone-otp'
    | '/api/verify-captcha'
    | '/api/verify-phone-otp'
    | '/api/order-notify'
    | '/api/payment-notify'
    | '/api/return-notify'
    | '/api/push-subscribe'
    | '/api/vapid-public-key'
    | '/profile'
    | '/admin/users'
    | '/admin/users/$id'
    | '/admin/orders/$id'
    | '/api/support-notify'
    | '/support'
    | '/support/$id'
    | '/admin/support'
    | '/admin/support/$id'
    | '/api/analytics-alerts-check'
    | '/api/analytics-cleanup'
    | '/api/analytics-error'
    | '/api/analytics-reports-run'
    | '/api/analytics-track'
    | '/api/search-log'
    | '/api/analytics-vitals'
    | '/admin/ai-console'
    | '/admin/search'
    | '/api/ai-console'
    | '/api/validate-coupon'
    | '/forgot-password'
    | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/wallet'
    | '/admin/analytics'
    | '/category/$name'
    | '/product/$slug'
    | '/orders/$id'
    | '/orders/$id/track'
    | '/admin'
    | '/admin/analytics/users'
    | '/admin/analytics/geographic'
    | '/admin/analytics/traffic'
    | '/admin/analytics/business'
    | '/admin/analytics/errors'
    | '/admin/analytics/realtime'
    | '/admin/analytics/alerts'
    | '/admin/analytics/reports'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/api/geocode'
    | '/api/rate-limit'
    | '/api/send-phone-otp'
    | '/api/verify-captcha'
    | '/api/verify-phone-otp'
    | '/api/order-notify'
    | '/api/payment-notify'
    | '/api/return-notify'
    | '/api/push-subscribe'
    | '/api/vapid-public-key'
    | '/profile'
    | '/admin/users'
    | '/admin/users/$id'
    | '/admin/orders/$id'
    | '/api/support-notify'
    | '/support'
    | '/support/$id'
    | '/admin/support'
    | '/admin/support/$id'
    | '/api/analytics-alerts-check'
    | '/api/analytics-cleanup'
    | '/api/analytics-error'
    | '/api/analytics-reports-run'
    | '/api/analytics-track'
    | '/api/search-log'
    | '/api/analytics-vitals'
    | '/admin/ai-console'
    | '/admin/search'
    | '/api/ai-console'
    | '/api/validate-coupon'
    | '/forgot-password'
    | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/orders'
    | '/privacy-policy'
    | '/returns-policy'
    | '/search'
    | '/shipping-policy'
    | '/terms'
    | '/wallet'
    | '/warranty-policy'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/returns'
    | '/admin/taxonomy'
    | '/admin/wallet'
    | '/admin/analytics'
    | '/category/$name'
    | '/product/$slug'
    | '/orders/$id'
    | '/orders/$id/track'
    | '/admin/'
    | '/admin/analytics/users'
    | '/admin/analytics/geographic'
    | '/admin/analytics/traffic'
    | '/admin/analytics/business'
    | '/admin/analytics/errors'
    | '/admin/analytics/realtime'
    | '/admin/analytics/alerts'
    | '/admin/analytics/reports'
    | '/admin/analytics/'
    | '/api/create-razorpay-order'
    | '/api/razorpay-webhook'
    | '/api/refund-razorpay-payment'
    | '/api/verify-razorpay-payment'
    | '/api/whatsapp-webhook'
    | '/api/geocode'
    | '/api/rate-limit'
    | '/api/send-phone-otp'
    | '/api/verify-captcha'
    | '/api/verify-phone-otp'
    | '/api/order-notify'
    | '/api/payment-notify'
    | '/api/return-notify'
    | '/api/push-subscribe'
    | '/api/vapid-public-key'
    | '/profile'
    | '/admin/users'
    | '/admin/users/$id'
    | '/admin/orders/$id'
    | '/api/support-notify'
    | '/support'
    | '/support/$id'
    | '/admin/support'
    | '/admin/support/$id'
    | '/api/analytics-alerts-check'
    | '/api/analytics-cleanup'
    | '/api/analytics-error'
    | '/api/analytics-reports-run'
    | '/api/analytics-track'
    | '/api/search-log'
    | '/api/analytics-vitals'
    | '/admin/ai-console'
    | '/admin/search'
    | '/api/ai-console'
    | '/api/validate-coupon'
    | '/forgot-password'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  WarrantyPolicyRoute: typeof WarrantyPolicyRoute
  CategoryNameRoute: typeof CategoryNameRoute
  ProductSlugRoute: typeof ProductSlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIdTrackRoute: typeof OrdersIdTrackRoute
  ApiCreateRazorpayOrderRoute: typeof ApiCreateRazorpayOrderRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
  ApiRefundRazorpayPaymentRoute: typeof ApiRefundRazorpayPaymentRoute
  ApiVerifyRazorpayPaymentRoute: typeof ApiVerifyRazorpayPaymentRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiRateLimitRoute: typeof ApiRateLimitRoute
  ApiSendPhoneOtpRoute: typeof ApiSendPhoneOtpRoute
  ApiVerifyCaptchaRoute: typeof ApiVerifyCaptchaRoute
  ApiVerifyPhoneOtpRoute: typeof ApiVerifyPhoneOtpRoute
  ApiOrderNotifyRoute: typeof ApiOrderNotifyRoute
  ApiPaymentNotifyRoute: typeof ApiPaymentNotifyRoute
  ApiReturnNotifyRoute: typeof ApiReturnNotifyRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiVapidPublicKeyRoute: typeof ApiVapidPublicKeyRoute
  ProfileRoute: typeof ProfileRoute
  ApiSupportNotifyRoute: typeof ApiSupportNotifyRoute
  SupportRoute: typeof SupportRoute
  SupportIdRoute: typeof SupportIdRoute
  ApiAnalyticsAlertsCheckRoute: typeof ApiAnalyticsAlertsCheckRoute
  ApiAnalyticsCleanupRoute: typeof ApiAnalyticsCleanupRoute
  ApiAnalyticsErrorRoute: typeof ApiAnalyticsErrorRoute
  ApiAnalyticsReportsRunRoute: typeof ApiAnalyticsReportsRunRoute
  ApiAnalyticsTrackRoute: typeof ApiAnalyticsTrackRoute
  ApiSearchLogRoute: typeof ApiSearchLogRoute
  ApiAnalyticsVitalsRoute: typeof ApiAnalyticsVitalsRoute
  ApiAiConsoleRoute: typeof ApiAiConsoleRoute
  ApiValidateCouponRoute: typeof ApiValidateCouponRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty-policy': {
      id: '/warranty-policy'
      path: '/warranty-policy'
      fullPath: '/warranty-policy'
      preLoaderRoute: typeof WarrantyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$name': {
      id: '/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof CategoryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/track': {
      id: '/orders/$id/track'
      path: '/orders/$id/track'
      fullPath: '/orders/$id/track'
      preLoaderRoute: typeof OrdersIdTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/returns': {
      id: '/admin/returns'
      path: '/returns'
      fullPath: '/admin/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taxonomy': {
      id: '/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/create-razorpay-order': {
      id: '/api/create-razorpay-order'
      path: '/api/create-razorpay-order'
      fullPath: '/api/create-razorpay-order'
      preLoaderRoute: typeof ApiCreateRazorpayOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay-webhook': {
      id: '/api/razorpay-webhook'
      path: '/api/razorpay-webhook'
      fullPath: '/api/razorpay-webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refund-razorpay-payment': {
      id: '/api/refund-razorpay-payment'
      path: '/api/refund-razorpay-payment'
      fullPath: '/api/refund-razorpay-payment'
      preLoaderRoute: typeof ApiRefundRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-razorpay-payment': {
      id: '/api/verify-razorpay-payment'
      path: '/api/verify-razorpay-payment'
      fullPath: '/api/verify-razorpay-payment'
      preLoaderRoute: typeof ApiVerifyRazorpayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order-notify': {
      id: '/api/order-notify'
      path: '/api/order-notify'
      fullPath: '/api/order-notify'
      preLoaderRoute: typeof ApiOrderNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-notify': {
      id: '/api/payment-notify'
      path: '/api/payment-notify'
      fullPath: '/api/payment-notify'
      preLoaderRoute: typeof ApiPaymentNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/return-notify': {
      id: '/api/return-notify'
      path: '/api/return-notify'
      fullPath: '/api/return-notify'
      preLoaderRoute: typeof ApiReturnNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-subscribe': {
      id: '/api/push-subscribe'
      path: '/api/push-subscribe'
      fullPath: '/api/push-subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapid-public-key': {
      id: '/api/vapid-public-key'
      path: '/api/vapid-public-key'
      fullPath: '/api/vapid-public-key'
      preLoaderRoute: typeof ApiVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/support-notify': {
      id: '/api/support-notify'
      path: '/api/support-notify'
      fullPath: '/api/support-notify'
      preLoaderRoute: typeof ApiSupportNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-alerts-check': {
      id: '/api/analytics-alerts-check'
      path: '/api/analytics-alerts-check'
      fullPath: '/api/analytics-alerts-check'
      preLoaderRoute: typeof ApiAnalyticsAlertsCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-cleanup': {
      id: '/api/analytics-cleanup'
      path: '/api/analytics-cleanup'
      fullPath: '/api/analytics-cleanup'
      preLoaderRoute: typeof ApiAnalyticsCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-error': {
      id: '/api/analytics-error'
      path: '/api/analytics-error'
      fullPath: '/api/analytics-error'
      preLoaderRoute: typeof ApiAnalyticsErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-reports-run': {
      id: '/api/analytics-reports-run'
      path: '/api/analytics-reports-run'
      fullPath: '/api/analytics-reports-run'
      preLoaderRoute: typeof ApiAnalyticsReportsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-track': {
      id: '/api/analytics-track'
      path: '/api/analytics-track'
      fullPath: '/api/analytics-track'
      preLoaderRoute: typeof ApiAnalyticsTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-log': {
      id: '/api/search-log'
      path: '/api/search-log'
      fullPath: '/api/search-log'
      preLoaderRoute: typeof ApiSearchLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics-vitals': {
      id: '/api/analytics-vitals'
      path: '/api/analytics-vitals'
      fullPath: '/api/analytics-vitals'
      preLoaderRoute: typeof ApiAnalyticsVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-console': {
      id: '/admin/ai-console'
      path: '/ai-console'
      fullPath: '/admin/ai-console'
      preLoaderRoute: typeof AdminAiConsoleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/ai-console': {
      id: '/api/ai-console'
      path: '/api/ai-console'
      fullPath: '/api/ai-console'
      preLoaderRoute: typeof ApiAiConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate-coupon': {
      id: '/api/validate-coupon'
      path: '/api/validate-coupon'
      fullPath: '/api/validate-coupon'
      preLoaderRoute: typeof ApiValidateCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/support/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAnalyticsRouteChildren {
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminAnalyticsUsersRoute: typeof AdminAnalyticsUsersRoute
  AdminAnalyticsGeographicRoute: typeof AdminAnalyticsGeographicRoute
  AdminAnalyticsTrafficRoute: typeof AdminAnalyticsTrafficRoute
  AdminAnalyticsBusinessRoute: typeof AdminAnalyticsBusinessRoute
  AdminAnalyticsErrorsRoute: typeof AdminAnalyticsErrorsRoute
  AdminAnalyticsRealtimeRoute: typeof AdminAnalyticsRealtimeRoute
  AdminAnalyticsAlertsRoute: typeof AdminAnalyticsAlertsRoute
  AdminAnalyticsReportsRoute: typeof AdminAnalyticsReportsRoute
}

const AdminAnalyticsRouteChildren: AdminAnalyticsRouteChildren = {
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminAnalyticsUsersRoute: AdminAnalyticsUsersRoute,
  AdminAnalyticsGeographicRoute: AdminAnalyticsGeographicRoute,
  AdminAnalyticsTrafficRoute: AdminAnalyticsTrafficRoute,
  AdminAnalyticsBusinessRoute: AdminAnalyticsBusinessRoute,
  AdminAnalyticsErrorsRoute: AdminAnalyticsErrorsRoute,
  AdminAnalyticsRealtimeRoute: AdminAnalyticsRealtimeRoute,
  AdminAnalyticsAlertsRoute: AdminAnalyticsAlertsRoute,
  AdminAnalyticsReportsRoute: AdminAnalyticsReportsRoute,
}

const AdminAnalyticsRouteWithChildren = AdminAnalyticsRoute._addFileChildren(
  AdminAnalyticsRouteChildren,
)

interface AdminRouteChildren {
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminTaxonomyRoute: typeof AdminTaxonomyRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSupportIdRoute: typeof AdminSupportIdRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRouteWithChildren
  AdminAiConsoleRoute: typeof AdminAiConsoleRoute
  AdminSearchRoute: typeof AdminSearchRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminTaxonomyRoute: AdminTaxonomyRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSupportIdRoute: AdminSupportIdRoute,
  AdminAnalyticsRoute: AdminAnalyticsRouteWithChildren,
  AdminAiConsoleRoute: AdminAiConsoleRoute,
  AdminSearchRoute: AdminSearchRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  OrdersRoute: OrdersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  WarrantyPolicyRoute: WarrantyPolicyRoute,
  CategoryNameRoute: CategoryNameRoute,
  ProductSlugRoute: ProductSlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  OrdersIdTrackRoute: OrdersIdTrackRoute,
  ApiCreateRazorpayOrderRoute: ApiCreateRazorpayOrderRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
  ApiRefundRazorpayPaymentRoute: ApiRefundRazorpayPaymentRoute,
  ApiVerifyRazorpayPaymentRoute: ApiVerifyRazorpayPaymentRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiRateLimitRoute: ApiRateLimitRoute,
  ApiSendPhoneOtpRoute: ApiSendPhoneOtpRoute,
  ApiVerifyCaptchaRoute: ApiVerifyCaptchaRoute,
  ApiVerifyPhoneOtpRoute: ApiVerifyPhoneOtpRoute,
  ApiOrderNotifyRoute: ApiOrderNotifyRoute,
  ApiPaymentNotifyRoute: ApiPaymentNotifyRoute,
  ApiReturnNotifyRoute: ApiReturnNotifyRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiVapidPublicKeyRoute: ApiVapidPublicKeyRoute,
  ProfileRoute: ProfileRoute,
  ApiSupportNotifyRoute: ApiSupportNotifyRoute,
  SupportRoute: SupportRoute,
  SupportIdRoute: SupportIdRoute,
  ApiAnalyticsAlertsCheckRoute: ApiAnalyticsAlertsCheckRoute,
  ApiAnalyticsCleanupRoute: ApiAnalyticsCleanupRoute,
  ApiAnalyticsErrorRoute: ApiAnalyticsErrorRoute,
  ApiAnalyticsReportsRunRoute: ApiAnalyticsReportsRunRoute,
  ApiAnalyticsTrackRoute: ApiAnalyticsTrackRoute,
  ApiSearchLogRoute: ApiSearchLogRoute,
  ApiAnalyticsVitalsRoute: ApiAnalyticsVitalsRoute,
  ApiAiConsoleRoute: ApiAiConsoleRoute,
  ApiValidateCouponRoute: ApiValidateCouponRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
